export const TODO_ADD_TO_EXIST = "TODO_ADD_TO_EXIST";
export const TODO_ADD_TO_ROOT = "TODO_ADD_TO_ROOT";
export const TODO_REMOVE = "TODO_REMOVE";
export const TODO_TOGGLE_COMPLETE = "TODO_TOGGLE_COMPLETE";
export const TODO_TOGGLE_SHOW_CHILDREN = "TODO_TOGGLE_SHOW_CHILDREN";
export const ALL_TODOS_REMOVE = "ALL_TODOS_REMOVE";
